#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_MAY,
    MUGSHOT_BRENDAN,
    MUGSHOT_VARUN,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_ALT,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
